#!/bin/sh
echo "                                                           "
echo "        The Skin HDFreaks is now being removed...          "
echo "                                                           "
